# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bored_no_more_app', '0005_event_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bored_no_more_app.User'),
            preserve_default=False,
        ),
    ]
